const fs = require('fs');
const path = require('path');
const indexPath = path.join(__dirname, 'dist', 'index.html');
let html = fs.readFileSync(indexPath, 'utf8');
html = html.replace(/<script src=/g, '<script type="module" src=');
html = html.replace(/\s+defer/g, '');
const seoTitle = '<title>SplitSaathi - Smart Expense Splitter App for Indians | Free Bill Splitting</title>';
const seoMeta = '<meta name="description" content="SplitSaathi - India ka best expense splitting app. Group trips, bill splitting, UPI payments, aur friends ke saath expenses track karo. Free!" /><meta name="keywords" content="expense splitter india, bill splitting app, group expense tracker, splitwise alternative india, trip expense manager, UPI payment split" /><meta name="robots" content="index, follow" /><link rel="canonical" href="https://splitsaathi.com/" /><meta property="og:title" content="SplitSaathi - Smart Expense Splitter" /><meta property="og:description" content="Group trips, shared bills, UPI settlements. India ka #1 free expense splitting app!" /><meta property="og:url" content="https://splitsaathi.com" /><meta property="og:type" content="website" /><meta name="theme-color" content="#1a56db" />';
<meta name="google-site-verification" content="eaPklf5hlEGiO455s0fYLPJDbpgKMDRYWXYc6Q_O4yA" />
html = html.replace('<title>SplitSaathi</title>', seoTitle + seoMeta);
fs.writeFileSync(indexPath, html);
console.log('✅ Fixed: type=module added');
console.log('✅ SEO meta tags added');
const adminDir = path.join(__dirname, 'dist', 'admin');
fs.mkdirSync(adminDir, { recursive: true });
fs.copyFileSync(path.join(__dirname, 'admin-panel.html'), path.join(adminDir, 'index.html'));
console.log('✅ Admin panel created at dist/admin/index.html');
const sitemap = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://splitsaathi.com/</loc><changefreq>weekly</changefreq><priority>1.0</priority></url></urlset>';
fs.writeFileSync(path.join(__dirname, 'dist', 'sitemap.xml'), sitemap);
console.log('✅ sitemap.xml created');
const robots = 'User-agent: *\nAllow: /\nSitemap: https://splitsaathi.com/sitemap.xml';
fs.writeFileSync(path.join(__dirname, 'dist', 'robots.txt'), robots);
console.log('✅ robots.txt created');